# curl -X GET http://localhost:8080/api/medecins
GET http://localhost:8080/api/medecins

###

# curl http://localhost:8080/api/medecins
GET http://localhost:8080/api/centres

###

# curl -X GET http://localhost:8080/api/centres/1/medecins
GET http://localhost:8080/api/centres/1/medecins

###

