GET http://localhost:8080/centers?name=Grand%20centre%20de%20vaccination

###

GET http://localhost:8080/centers?city=Paris

###

DELETE http://localhost:8080/center/0

###

POST http://localhost:8080/centers
Content-Type: application/json

{
  "id": 0,
  "name": "Grand centre de vaccination",
  "addressId": 4
}