GET http://localhost:8080/centers?name=Grand%20centre%20de%20vaccination

###

GET http://localhost:8080/centers

###

GET http://localhost:8080/centers?city=Paris

###

DELETE http://localhost:8080/center/0

###

POST http://localhost:8080/centers
Content-Type: application/json

{
  "name": "Grand centre de vaccination",
  "address": {
    "city": "Paris",
    "postalCode": "75015",
    "street": "14 rue du Grand Centre"
  }
}