GET http://localhost:8080/doctors

###

DELETE http://localhost:8080/doctor/0

###

POST http://localhost:8080/doctors
Content-Type: application/json

{
  "firstname": "Gregory",
  "lastname": "House",
  "address": {
    "street": "14 rue du Four",
    "city": "Deauville",
    "postalCode": "14800"
  }
}